a = input('Digite algo:')
print('O tipo primitivo sesse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em MAISÚSCULAS?', a.isupper())
print('Está emminúnsculas?', a.islower())
print('Está capitalizada(mesclada)?', a.istitle())
